python3 DAE.py
python3 DAE.py
python3 DAE.py
python3 DAE.py
python3 DAE.py
python3 DAE.py
python3 DAE.py
python3 DAE.py
python3 DAE.py
python3 DAE.py
python3 DAE.py
python3 DAE.py
python3 DAE.py
python3 DAE.py
python3 DAE.py
python3 DAE.py
python3 DAE.py
python3 DAE.py
python3 DAE.py
# 100 epoch